name = "Antlr4Grammar"
version = "0.1.0"
defaultTargets = ["Antlr4Grammar"]

[[require]]
name = "LeanParser"
path = "../../LeanParser"

[[lean_lib]]
name = "Antlr4Grammar"
deps = ["LeanParser"]
globs = ["Lexer"]

[[lean_exe]]
name = "test"
srcDir = "."
root = "Test"
deps = ["Antlr4Grammar"]
